### ISSUE TITLE
Please tell me more

### ISSUE THREAD

**Issue by nikolas2222** [ruperto7/DjangoDjongo7#5]
thanks

**Comment by ruperto7** [comment]
hi Nikolas,
thank you for your interest to learn about using github for team collaboration.
Please have a look at:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository

Please let me know if you are able to clone https://github.com/ruperto7/DjangoDjongo7

From there, we shall chat again. thank you.

(tip:, you could install git first if needed, then open a command window into your c:\users\<yourname> folder then type: git clone https://github.com/ruperto7/DjangoDjongo7 
)
